# remap prefix to Ctrl + a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g default-terminal "screen-256color"

# new window with current directory
bind c new-window -c "#{pane_current_path}"

# remap split window keys
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# mouse behavior
#setw -g mode-mouse on
